/**
 * ulunas_matlab_weights.c — Weight Definitions
 * =============================================
 * The auto-generated ulunas_matlab_weights.h contains all quantized
 * weight arrays as static const definitions (generated by Python from
 * the pre-quantized .mat files).
 */
#include "ulunas_matlab_weights.h"
