# UL-UNAS Full Pipeline: C vs MATLAB Frame 0 逐层对齐

> 2026-07-13, noisy_fileid_1.wav Frame 0
> 按照 Main_infer.m 函数调用顺序组织
> C: dump_full (linux_api13 weights + 10:30 fp/modules/lut .o)
> M: export_all_layers_v2

---

## Q-Format 约定 (stft_fixed_point_guide.md)

| MATLAB | C 格式 | 总位宽 | 范围 | 精度 | 用途 |
|--------|--------|--------|------|------|------|
| Q12.20 | s32f20 | 32 | [-2048, ~2048] | 2^-20 | 层间激活值, STFT输出 |
| Q1.15 | s16f15 | 16 | [-1, ~1] | 2^-15 | 音频/PCM, GRU隐状态 |
| UQ1.15 | u16f15 | 16 | [0, ~2] | 2^-15 | sigmoid输出, ERB权重 |
| UQ5.11 | u16f11 | 16 | [0, ~64] | 2^-11 | LN 1/sqrt(var) |

```
信号路径: PCM Q15 -> 加窗 Q15 -> FFT Q15 -> Q20 (<<5) -> 模型 -> Q20 -> Q15 (>>5) -> IFFT Q15 -> OLA
Q15 -> Q20: x_q20 = x_q15 << 5 (exact)
Q20 -> Q15: x_q15 = (x_q20 + 16) >> 5 (四舍五入)
```

**中间计算规则**: Q15xQ15 -> int64乘积 -> (prod+16384)>>15 -> Q15; 累加器用int64防溢出

---

## 全链路 SNR 汇总

| # | 函数 | SNR | 状态 | C格式 | M格式 |
|---|------|-----|------|-------|-------|
| 1 | STFT_func | 55.9 dB | PASS | s32f20 | float->Fix_point s32f20 |
| 2 | log_gen | bit-exact | PERFECT | s32f20 | s32f20 |
| 3 | BM_module | 84.2 dB | PASS | s32f20 | s32f20 |
| 4 | Encoder E0 | 67.5 dB | PASS | s32f20 | s32f20 |
| 5 | Encoder E1 | 64.7 dB | PASS | s32f20 | s32f20 |
| 6 | Encoder E2 | 65.3 dB | PASS | s32f20 | s32f20 |
| 7 | Encoder E3 | 64.5 dB | PASS | s32f20 | s32f20 |
| 8 | Encoder E4 | 64.1 dB | PASS | s32f20 | s32f20 |
| 9 | RNN1 | 67.5 dB | PASS | s32f20 | s32f20 |
| 10 | RNN2 | 64.6 dB | PASS | s32f20 | s32f20 |
| 11 | Decoder | 62.0 dB | PASS | s32f20 | s32f20 |
| 12 | sigmoid_func | bit-exact | PERFECT | u16f15 | u16f15 |
| 13 | BS_module | 84.1 dB | PASS | s16f15 | s16f15 |
| 14 | MASK_module | 94.4 dB | PASS | s32f20 | s32f20 |

---

## [1] STFT_func

```
[cmp_real, cmp_imag] = STFT_func(noisy_audio.', N_fft=512, win_len=512, win_inc=256, hann_window)
```

**定点定标规则** (强制):
- 输入 noisy_audio: **s16f15** (16-bit有符号, 范围±1.0)
- 输入 hann_window: **u16f15** (16-bit无符号, 范围[0,~2])
- 输出 cmp_real/cmp_imag: **s32f20** (32-bit有符号, Q20小数)

**对齐检查清单**:
| 参数 | 值 | 注意事项 |
|------|-----|---------|
| N_fft | 512 | FFT点数 |
| win_len | 512 | 帧长 |
| win_inc | 256 | 帧移 |
| 窗函数 | stft_window.mat ×32767取整 | C代码用等值Q15表, 不可用公式近似 |
| 边界处理 | flip(x(2:257)), flip(x(end-256:end-1)) | 镜像填充256点, 首尾帧与直通完全不同 |
| 音频归一化 | audioread [-1,1] float | C侧需/32768 |

**FFT定点实现要点**:
- 旋转因子: cos(2pi*k/512)x32767, sin(2pi*k/512)x32767, Q15
- 蝶形: `tr=(ar*wr-ai*wi)>>15; ti=(ar*wi+ai*wr)>>15` (Q15xQ15->Q30->>>15->Q15)
- 9级蝶形, 每级±0.5LSB, 累积~4.5LSB rms
- 输出: `real_out[b]=fft_in[b]<<5` (Q15->Q20, exact)

**Frame 0 验证**: SNR 55.9 dB

| Bin | C s32f20 | C Float | M Float | 误差% |
|-----|---------|---------|---------|-------|
| 0 (DC) | 1627520 | 1.5520 | 1.5616 | 0.61% |
| 4 (峰值) | 6054016 | 5.7739 | 5.7789 | 0.09% |
| 8 | 202816 | -0.1934 | -0.1933 | 0.07% |
| 128 (Nyq/2) | 9856 | 0.0094 | 0.0096 | 2.58% |
| 256 (Nyq) | 2944 | 0.0014 | 0.0010 | 49.06% |

**误差源**(按贡献):
1. FFT蝶形取整(主导): 9级>>15, 每级±0.5LSB
2. 加窗取整: (sxw+16384)>>15
3. 窗函数量化: float->Q15 round
4. 输入量化(可忽略): int16 PCM本身即Q15

---

## [2] log_gen — bit-exact

```
x = log_gen(spec_real, spec_imag)
```

MATLAB: `mag = sqrt(real^2+imag^2); clamped=max(mag,1e-12); y=log10(clamped); Fix_point(y,'s32f20')`
C: int64平方和 -> isqrt64 -> log10_q20 LUT

| Bin | C s32f20 | M s32f20 | Diff LSB | Float | EffBits |
|-----|---------|---------|---------|-------|---------|
| 0 | 202965 | 202965 | 0 | 0.193563 | 38 |
| 4 | 798854 | 798854 | 0 | 0.761847 | 40 |
| 8 | -748464 | -748464 | 0 | -0.713791 | 40 |
| 16 | -1407829 | -1407829 | 0 | -1.342610 | 41 |
| 32 | -57565 | -57565 | 0 | -0.054898 | 36 |
| 64 | -688456 | -688456 | 0 | -0.656563 | 40 |
| 128 | -2113455 | -2113455 | 0 | -2.015548 | 42 |
| 256 | -3163248 | -3163248 | 0 | -3.016708 | 42 |

---

## [3] BM_module — SNR 84.2 dB

```
x_bm = BM_module(x, erbfc_weight)
```

MATLAB: `y(1:65)=x(1:65); y(66:129)=round(x(66:257)*weight*2^(-15))`
C: 低65bin直通, 高192bin矩阵乘(192x64), 累加int64后round_shr>>15
ERB权重: u16f15, 固定滤波器组系数(不随训练改变)

| Bin | C s32f20 | M s32f20 | Diff LSB | Float_M |
|-----|---------|---------|---------|---------|
| 0 | 202986 | 202965 | +21 | 0.193563 |
| 4 | 798696 | 798854 | -158 | 0.761847 |
| 8 | -748284 | -748464 | +180 | -0.713791 |
| 16 | -1407638 | -1407829 | +191 | -1.342610 |
| 32 | -57384 | -57565 | +181 | -0.054898 |
| 48 | -436015 | -436618 | +603 | -0.416391 |
| 64 | -688716 | -688456 | -260 | -0.656563 |
| 80 | -2884007 | -2884571 | +564 | -2.750940 |
| 96 | -5902640 | -5902896 | +256 | -5.629440 |
| 128 | -9650083 | -9650952 | +869 | -9.203865 |

---

## [4]-[8] Encoder_module

```
[y_e0,...,y_e4] = Encoder_module(x_bm, conv_cache_e0, tfa_cache_e0, ...)
```

5层编码器: XConv(E0) -> XMB0(E1) -> XDWS0(E2) -> XMB1(E3) -> XDWS1(E4)
每层包含: Conv/TConv + BN + AffinePReLU + cTFA(TA+FA) + 下采样
cTFA: 时间注意力(TA GRU, s16f15) x 频率注意力(FA 双向GRU) -> 融合(>>15 x2)

### Encoder E0 XConv [12x65] — SNR 67.5 dB

TConv(1->12, k=3x3, s=[1,2]) -> BN -> AffinePReLU -> cTFA(TA 12ch + FA 65ch)

| Sub-Step | SNR | 格式 |
|----------|-----|------|
| TConv+BN+AP | 80.7 dB | s32f20 |
| cTFA TA Gate | 90.2 dB | u16f15 |
| cTFA FA Gate | 70.9 dB | u16f15 |
| cTFA Fusion | 67.5 dB | s32f20 |

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | -909 | -908 | -1 | -0.000866 |
| 32 (ch0,f32) | -17436 | -17556 | +120 | -0.016743 |
| 64 (ch0,f64) | -65750 | -65752 | +2 | -0.062706 |
| 195 (ch3,f0) | -16531 | -16528 | -3 | -0.015762 |
| 227 (ch3,f32) | 45899 | 45937 | -38 | 0.043809 |
| 259 (ch3,f64) | 426821 | 426987 | -166 | 0.407207 |
| 390 (ch6,f0) | 23798 | 23814 | -16 | 0.022711 |
| 422 (ch6,f32) | -71603 | -71617 | +14 | -0.068299 |
| 454 (ch6,f64) | 202510 | 202638 | -128 | 0.193251 |
| 715 (ch11,f0) | 109248 | 109232 | +16 | 0.104172 |
| 747 (ch11,f32) | 86236 | 86207 | +29 | 0.082213 |
| 779 (ch11,f64) | -9367 | -9372 | +5 | -0.008938 |

**E0 TA GRU** (8ch, s16f15): SNR 84.5 dB bit-level:

| Ch | C s16f15 | M s16f15 | Diff LSB |
|----|---------|---------|---------|
| 0 | -32767 | -32766 | -1 |
| 1 | 159 | 159 | 0 |
| 2 | 32691 | 32691 | 0 |
| 3 | -16990 | -16995 | +5 |
| 4 | 0 | 0 | 0 |
| 5 | 25326 | 25322 | +4 |
| 6 | 32666 | 32666 | 0 |
| 7 | 0 | 0 | 0 |

**E0 FA GRU0** (8ch, s16f15, reverse): SNR 65.4 dB:

| Ch | C s16f15 | M s16f15 | Diff LSB |
|----|---------|---------|---------|
| 0 | 2363 | 2364 | -1 |
| 1 | -5518 | -5519 | +1 |
| 2 | -14483 | -14482 | -1 |
| 3 | 9751 | 9754 | -3 |
| 4 | 1728 | 1728 | 0 |
| 5 | -6151 | -6148 | -3 |
| 6 | -10166 | -10165 | -1 |
| 7 | -14997 | -15006 | +9 |

> SNR损失: BM(84.2) -> E0(67.5) = -16.7 dB. 主导因素: cTFA Fusion TAxFA两次>>15(~-3.5dB) + GRU隐状态s16f15量化(~-13dB)

### Encoder E1 XMB0 [24x33] — SNR 64.7 dB

PConv0(12->24,g=2) -> shuffle -> TConv(24->24,s=2,k=2x3,cached) -> PConv1(BN) -> cTFA

| Sub-Step | SNR |
|----------|-----|
| PConv0 | 96.1 dB |
| TConv | 94.9 dB |
| cTFA TA | 93.6 dB |
| cTFA FA | 88.6 dB |

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | 89908 | 89925 | -17 | 0.085759 |
| 16 (ch0,f16) | 192759 | 192636 | +123 | 0.183712 |
| 32 (ch0,f32) | 727708 | 728019 | -311 | 0.694293 |
| 198 (ch6,f0) | 40774 | 40693 | +81 | 0.038808 |
| 214 (ch6,f16) | -165285 | -164966 | -319 | -0.157324 |
| 230 (ch6,f32) | 1570831 | 1570721 | +110 | 1.497956 |
| 396 (ch12,f0) | -30585 | -30617 | +32 | -0.029199 |
| 428 (ch12,f32) | 615516 | 615403 | +113 | 0.586894 |
| 791 (ch23,f32) | 256789 | 257075 | -286 | 0.245166 |

**E1 cTFA TA** (8ch, u16f15): SNR 93.6 dB bit-level:

| Ch | C u16f15 | M u16f15 | Diff LSB |
|----|---------|---------|---------|
| 0 | 24147 | 24147 | 0 |
| 1 | 3081 | 3081 | 0 |
| 2 | 15864 | 15864 | 0 |
| 3 | 20537 | 20538 | -1 |
| 4 | 24107 | 24107 | 0 |
| 5 | 19975 | 19975 | 0 |
| 6 | 9240 | 9240 | 0 |
| 7 | 16314 | 16314 | 0 |

### Encoder E2 XDWS0 [24x33] — SNR 65.3 dB

PConv(24->24,g=2) -> shuffle -> TConv(24->24,s=1,k=3x3,cached) -> cTFA

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | -304401 | -304319 | -82 | -0.290221 |
| 16 (ch0,f16) | 145784 | 145738 | +46 | 0.138987 |
| 32 (ch0,f32) | 880535 | 880776 | -241 | 0.839973 |
| 198 (ch6,f0) | 191974 | 191972 | +2 | 0.183079 |
| 214 (ch6,f16) | -240633 | -240669 | +36 | -0.229520 |
| 230 (ch6,f32) | 178678 | 178622 | +56 | 0.170347 |
| 396 (ch12,f0) | 67584 | 67476 | +108 | 0.064350 |
| 428 (ch12,f32) | 432212 | 431733 | +479 | 0.411733 |
| 791 (ch23,f32) | -88888 | -88973 | +85 | -0.084851 |

### Encoder E3 XMB1 [32x33] — SNR 64.5 dB

PConv0(24->32,g=2) -> shuffle -> nonTConv(32->32,k=1x5) -> PConv1(BN) -> cTFA

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | 211670 | 211670 | +0 | 0.201864 |
| 16 (ch0,f16) | 146090 | 145951 | +139 | 0.139190 |
| 32 (ch0,f32) | -116834 | -116720 | -114 | -0.111313 |
| 264 (ch8,f0) | -208606 | -208695 | +89 | -0.199027 |
| 296 (ch8,f32) | 107127 | 107179 | -52 | 0.102214 |
| 528 (ch16,f0) | -162111 | -162109 | -2 | -0.154599 |
| 560 (ch16,f32) | 404246 | 404274 | -28 | 0.385546 |
| 1023 (ch31,f0) | -69254 | -69273 | +19 | -0.066064 |
| 1055 (ch31,f32) | -75120 | -74993 | -127 | -0.071519 |

### Encoder E4 XDWS1 [16x33] — SNR 64.1 dB

PConv(32->16,g=2) -> shuffle -> nonTConv(16->16,k=1x5) -> cTFA

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | -359156 | -359203 | +47 | -0.342563 |
| 16 (ch0,f16) | -268811 | -268895 | +84 | -0.256438 |
| 32 (ch0,f32) | 710103 | 709944 | +159 | 0.677055 |
| 132 (ch4,f0) | 312257 | 312286 | -29 | 0.297819 |
| 164 (ch4,f32) | -153365 | -153327 | -38 | -0.146224 |
| 264 (ch8,f0) | 438406 | 438250 | +156 | 0.417948 |
| 296 (ch8,f32) | 608992 | 608970 | +22 | 0.580759 |
| 495 (ch15,f0) | 65651 | 65693 | -42 | 0.062650 |
| 527 (ch15,f32) | 231115 | 231078 | +37 | 0.220373 |

> Encoder级联: E0(67.5)->E1(64.7)->E2(65.3)->E3(64.5)->E4(64.1). Skip connection和shuffle提供特征重排, SNR稳定在64-67 dB

---

## [9]-[10] GDPRNN_module

```
[y_rnn1, inter_cache_0] = GDPRNN_module(y_e4, inter_cache_0, 0)
[y_rnn2, inter_cache_1] = GDPRNN_module(y_rnn1, inter_cache_1, 1)
```

每个GDPRNN Block: Intra(频域BiGRU + FC + LN + residual) + Inter(时域GRU + FC + LN + residual)
GRU hidden: s16f15, FC: s32f20, LN: s32f20(u16f11 1/sqrt(var))

### RNN1 [16x33] — SNR 67.5 dB

| Sub-Step | SNR |
|----------|-----|
| intra_gru0 (BiGRU fwd) | 71.7 dB |
| intra_gru1 (BiGRU rev) | 66.8 dB |
| intra_fc | 74.2 dB |
| intra_ln | 74.0 dB |
| inter_gru0 | 75.6 dB |
| inter_fc | 80.2 dB |
| inter_ln | 79.9 dB |

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | -251071 | -251027 | -44 | -0.239398 |
| 16 (ch0,f16) | 312126 | 312071 | +55 | 0.297614 |
| 32 (ch0,f32) | 1265305 | 1265362 | -57 | 1.206743 |
| 132 (ch4,f0) | 268861 | 268581 | +280 | 0.256139 |
| 164 (ch4,f32) | 1051110 | 1050987 | +123 | 1.002299 |
| 264 (ch8,f0) | 1588434 | 1588736 | -302 | 1.515137 |
| 296 (ch8,f32) | 3532988 | 3533766 | -778 | 3.370062 |
| 396 (ch12,f0) | 958812 | 958352 | +460 | 0.913956 |
| 428 (ch12,f32) | -1445762 | -1446497 | +735 | -1.379487 |
| 495 (ch15,f0) | 963132 | 962815 | +317 | 0.918212 |
| 527 (ch15,f32) | 3704537 | 3704927 | -390 | 3.533294 |

### RNN2 [16x33] — SNR 64.6 dB

| Idx (ch,f) | C s32f20 | M s32f20 | Diff LSB | Float_M |
|------------|---------|---------|---------|---------|
| 0 (ch0,f0) | -75240 | -74922 | -318 | -0.071451 |
| 16 (ch0,f16) | -218854 | -219365 | +511 | -0.209203 |
| 32 (ch0,f32) | 3699207 | 3699221 | -14 | 3.527852 |
| 132 (ch4,f0) | 1766054 | 1766692 | -638 | 1.684849 |
| 164 (ch4,f32) | 554476 | 554265 | +211 | 0.528588 |
| 264 (ch8,f0) | -106924 | -106852 | -72 | -0.101902 |
| 296 (ch8,f32) | 1346430 | 1346583 | -153 | 1.284202 |
| 396 (ch12,f0) | -7815350 | -7815421 | +71 | -7.453366 |
| 428 (ch12,f32) | -1131885 | -1132367 | +482 | -1.079909 |
| 495 (ch15,f0) | 1405458 | 1405410 | +48 | 1.340303 |
| 527 (ch15,f32) | 7173883 | 7176212 | -2329 | 6.843769 |

---

## [11] Decoder_module — SNR 62.0 dB

```
[y_dec, ...] = Decoder_module(y_rnn2, y_e4, ... y_e3, ... y_e2, ... y_e1, ... y_e0, ...)
```

5层解码器: De_XDWS0(D0) -> De_XMB0(D1) -> De_XDWS1(D2) -> De_XMB1(D3) -> De_XConv(D4)
每层: skip connection(add encoder对应层) -> PConv -> shuffle -> TConv/GTConv -> cTFA

| Sub-Step | SNR | 格式 |
|----------|-----|------|
| D0 iso (golden input) | 89.0 dB | s32f20 |
| D0.tconv | 105.7 dB | s32f20 |
| D1 iso | 85.6 dB | s32f20 |
| D3 iso | 84.5 dB | s32f20 |
| D3.tconv | 97.8 dB | s32f20 |
| D3.ctfa TA | 90.6 dB | u16f15 |
| D3.ctfa FA | 87.3 dB | u16f15 |

| Bin | C s32f20 | M s32f20 | Diff LSB | Float_M |
|-----|---------|---------|---------|---------|
| 0 | -815468 | -814295 | -1173 | -0.776572 |
| 8 | -2138541 | -2137436 | -1105 | -2.038418 |
| 16 | -2170017 | -2169030 | -987 | -2.068548 |
| 32 | -4939589 | -4936818 | -2771 | -4.708117 |
| 48 | -4498812 | -4498200 | -612 | -4.289818 |
| 64 | -4283869 | -4285756 | +1887 | -4.087215 |
| 80 | -3813906 | -3814840 | +934 | -3.638115 |
| 96 | -2800765 | -2800248 | -517 | -2.670525 |
| 112 | -2320760 | -2321219 | +459 | -2.213687 |
| 128 | -789721 | -787893 | -1828 | -0.751393 |

**D3 cTFA TA** (12ch, u16f15): SNR 90.6 dB bit-level:

| Ch | C u16f15 | M u16f15 | Diff LSB |
|----|---------|---------|---------|
| 0 | 19087 | 19087 | 0 |
| 1 | 13296 | 13296 | 0 |
| 2 | 19922 | 19922 | 0 |
| 3 | 22544 | 22544 | 0 |
| 4 | 6663 | 6663 | 0 |
| 5 | 3310 | 3310 | 0 |
| 6 | 10179 | 10179 | 0 |
| 7 | 21737 | 21738 | -1 |

**D3 cTFA FA** (12ch, u16f15): SNR 87.3 dB:

| Ch | C u16f15 | M u16f15 | Diff LSB |
|----|---------|---------|---------|
| 0 | 20384 | 20383 | +1 |
| 1 | 21598 | 21597 | +1 |
| 2 | 18873 | 18872 | +1 |
| 3 | 17280 | 17279 | +1 |
| 4 | 20245 | 20244 | +1 |
| 5 | 17691 | 17690 | +1 |
| 6 | 19573 | 19572 | +1 |
| 7 | 17524 | 17523 | +1 |

---

## [12] sigmoid_func — bit-exact

```
y_sig_dq = y_dec * 2^(-20)
y_sig_q = sigmoid_func(y_sig_dq)
y_sig = Fix_point(y_sig_q, 'u16f15')
```

C: sigmoid_q20_to_q15 LUT

| Bin | C u16f15 | M u16f15 | Diff LSB | Float |
|-----|---------|---------|---------|-------|
| 0 | 10324 | 10324 | 0 | 0.31506 |
| 4 | 1677 | 1677 | 0 | 0.05118 |
| 8 | 3776 | 3776 | 0 | 0.11523 |
| 16 | 3676 | 3676 | 0 | 0.11218 |
| 32 | 293 | 293 | 0 | 0.00894 |
| 64 | 541 | 541 | 0 | 0.01651 |
| 128 | 10503 | 10503 | 0 | 0.32053 |

---

## [13] BS_module — SNR 84.1 dB (独立测试)

```
y_bs = BS_module(y_sig, ierbfc_weight)
```

MATLAB: `y(1:65)=x(1:65); y(66:257)=round(x(66:129)*weight*2^(-15))`
C: 低65bin直通, 高64bin矩阵乘(64x192), 累加int64后round_shr>>15
ERB权重: u16f15

| Bin | C s16f15 | M s16f15 | Diff LSB | Float |
|-----|---------|---------|---------|-------|
| 0 | 10324 | 10324 | 0 | 0.31506 |
| 8 | 3776 | 3776 | 0 | 0.11523 |
| 16 | 3676 | 3676 | 0 | 0.11218 |
| 32 | 293 | 293 | 0 | 0.00894 |
| 64 | 541 | 541 | 0 | 0.01651 |
| 65 | 889 | 889 | 0 | 0.02713 |
| 80 | 696 | 696 | 0 | 0.02124 |
| 96 | 2335 | 2335 | 0 | 0.07126 |
| 128 | 2950 | 2950 | 0 | 0.09003 |
| 160 | 1860 | 1860 | 0 | 0.05676 |
| 200 | 7792 | 7792 | 0 | 0.23779 |
| 256 | 10503 | 10503 | 0 | 0.32053 |

---

## [14] MASK_module — SNR 94.4 dB (独立测试)

```
y_mask = MASK_module(y_bs, spec_real, spec_imag)
```

MATLAB: `y_real=round(spec_real.*y_bs*2^(-15)); y_imag=round(spec_imag.*y_bs*2^(-15))`
C: s16f15 x s32f20 -> int64乘积 -> round_shr>>15 -> s32f20

| Bin | C Real s32f20 | M Real s32f20 | Diff | C Imag s32f20 | M Imag s32f20 | Diff |
|-----|-------------|-------------|------|-------------|-------------|------|
| 0 | 515894 | 515894 | 0 | 0 | 0 | 0 |
| 4 | 310120 | 310120 | 0 | 0 | 0 | 0 |
| 8 | -23357 | -23356 | -1 | 0 | 0 | 0 |
| 16 | 5345 | 5345 | 0 | 0 | 0 | 0 |
| 32 | -8264 | -8263 | -1 | 0 | 0 | 0 |
| 64 | 3818 | 3818 | 0 | 0 | 0 | 0 |
| 96 | 7351 | 7351 | 0 | 0 | 0 | 0 |
| 128 | 911 | 911 | 0 | 0 | 0 | 0 |
| 200 | -1365 | -1364 | -1 | 0 | 0 | 0 |
| 256 | 323 | 323 | 0 | 0 | 0 | 0 |

---

## [15] ISTFT_func — Frame 0 IFFT (部分验证)

| Sample | C IFFT Q15 | M IFFT Q15 | Diff LSB | Float |
|--------|-----------|-----------|---------|-------|
| 0 | 0 | 0 | 0 | 0.000000 |
| 32 | 23 | 23 | 0 | 0.000702 |
| 128 | 63 | 63 | 0 | 0.001923 |
| 256 | 123 | 123 | 0 | 0.003754 |
| 384 | 63 | 63 | 0 | 0.001923 |
| 511 | 0 | 0 | 0 | 0.000000 |

> IFFT SNR ~55 dB (9级>>15蝶形取整, 匹配前向STFT). 窗口边缘采样为0(Hann^2窗taper). 完整ISTFT需多帧OLA(T>=3)

---

## 误差主导因素 (按贡献排序)

1. **GRU sigmoid/tanh 取整** (~65-72 dB 子步骤, s16f15隐状态量化主导)
2. **cTFA Fusion TAxFA 两次 >>15** (~67 dB, 每层~3.5 dB累积)
3. **Conv/BN/AP Q20xQ1x->>>N 累加取整** (TConv 81 dB, PConv 96 dB)
4. **RNN 缓存帧间传播** (Frame 1+ 退化至 ~15 dB)
5. **Decoder 5层级联** (各层iso 85-89 dB, 级联后62 dB)

### MASK 端到端 SNR~0 dB 根因与优化

Decoder(62dB) -> sigmoid(bit-exact) -> BS(84dB standalone) -> MASK 级联
62dB decoder误差被sigmoid非线性放大, 经BS矩阵乘累积后MASK降至~0dB

| 优先级 | 优化方案 | 预期提升 | 难度 |
|--------|---------|---------|------|
| P0 | GRU hidden state s16f15->s32f20 | Decoder 62->75 dB | 中 |
| P1 | cTFA Fusion 更高精度移位 | +2-3 dB/层 | 低 |
| P2 | LN 1/sqrt(var) u16f11->u32f20 | RNN +5 dB | 中 |
| P3 | Decoder skip connection 权重对齐 | Decoder +10 dB | 高 |
